// 1.use blog
// 2.db.createCollection('articles')
// 3.db.articles.insertMany(blogs);
// 4. db.COLLECTION_NAME.find()
// 5.db.articles.find({_id: 'random1'})
// 6.db.articles.findOne({title: 'blog2'})
// 7.db.articles.findOne({'author.name' :'name3'})
// 8.db.articles.find({tags:'css'})
// 9.db.articles.update({_id:'random1'},{title:'blog0'})
// 10.db.articles.update({'author.name':'name2'},{$set:{'author.name':'unknown'}})
// 11.db.articles.updateMany({},{$rename: {'details':'description'}}, {multi:true})
// 12.db.articles.update({title:'blog2'},{$push:{tags:'java'}})
// db.users.find({gender:'Male' ,sports:'cricket'})
// db.users.update({name:'Steve Ortega'},{$push:{sports:'golf'}})
// db.users.find({sports:{$in:['football','cricket']}}).count()